### ISSUE TITLE
A few more broken links

### ISSUE THREAD

**Issue by Nikolozi** [audiokit/audiokit.github.io#45]
Found some more broken links. I came across one and then I thought I should run the site through a broken link checker utility. These 3 came up:

1. AKMidiListener (http://audiokit.io/Protocols/AKMidiListener.html) on page http://audiokit.io/Classes/AKMidi.html
2. FM Oscillator link (http://audiokit.io/examples/SwiftFMOScillator/) on page http://audiokit.io/features/
3. The first appearance of AKControl (http://audiokit.io/docs/Classes/AKControl.html) on page http://audiokit.io/parameters/

**Comment by aure** [comment]
Thanks, fixed them!
