### ISSUE TITLE
The "Play Audio File" example on the website is confusing

### ISSUE THREAD

**Issue by alexdmiller** [audiokit/audiokit.github.io#62]
This page feels incomplete: http://audiokit.io/examples/swift/PlayAudioFile/

It says that, "A path to the audio file that will be played ("blaster.aiff") is defined in the code below from "AudioFilePlayer.m"." But it's not specific about whether you should import AudioFilePlayer, extend it, or just copy and paste the code from AudioFilePlayer.

If you're supposed to edit the code that's already there, then its placement inside of AudioKit/Utilities/Instruments/File Players/ is odd. If that's the case, it should be in an Examples folder, not the Utilities folder.

I opened an issue on the AudioKit project (https://github.com/audiokit/AudioKit/issues/262) and it was closed. But the fix that was committed doesn't address issue, so I'm re-opening on this project.

**Comment by aure** [comment]
There is nothing wrong with these instructions. Are you sure you're looking at the right repo?  This is the AudioFilePlayer.swift you didn't think existed: https://github.com/audiokit/Examples/blob/master/iOS%20Examples/Swift/PlayAudioFile/PlayAudioFile/AudioFilePlayer.swift

**Comment by alexdmiller** [comment]
You're right, I was searching in https://github.com/audiokit/AudioKit; I didn't realize there was a separate repository for the examples.

Can I suggest linking to the exact file from http://audiokit.io/examples/swift/PlayAudioFile/? Unless I knew to search for the file in the Examples repository, I wouldn't know where else to find it. I can't imagine a normal user looking through the examples would understand to do that. (Unless maybe I'm missing something?)

Thanks!

**Comment by aure** [comment]
Good idea, done!

**Comment by narner** [comment]
Great suggestion @alexdmiller, thanks!
