### ISSUE TITLE
Search at top of page

### ISSUE THREAD

**Issue by Alasdair-Munday** [audiokit/audiokit.github.io#66]
The search currently hits the whole of  Google, the hidden input field holding the audiokit address needs to be changed from q to as_sitesearch

**Comment by Alasdair-Munday** [comment]
Line 30 of _includes/header.HTML

Change the name attribute to name="as_sitesearch" and change the value to value="audiokit.io"

**Comment by aure** [comment]
Thanks, do you want to make a pull request with the fixes?

**Comment by Alasdair-Munday** [comment]
Sure, as soon as I get near a PC

**Comment by Alasdair-Munday** [comment]
Pull request submitted :)

**Comment by aure** [comment]
Thanks!
