### ISSUE TITLE
Missing images on Examples page 

### ISSUE THREAD

**Issue by narner** [audiokit/audiokit.github.io#70]
See screenshot for details
![screen shot 2016-06-20 at 10 37 18 am](https://cloud.githubusercontent.com/assets/2131591/16198236/2d176e9c-36d3-11e6-8b0b-b36913402bd7.png)

**Comment by aure** [comment]
fixed, you could have done it too. :)

**Comment by narner** [comment]
@aure On my work laptop so didn't have everything set-up :)

**Comment by aure** [comment]
Just giving you a hard time, hence the smiley.
