### ISSUE TITLE
Hard to read text on main page gallery

### ISSUE THREAD

**Issue by narner** [audiokit/audiokit.github.io#75]
Some of the text is hard to read on the main page "gallery" is hard to read:

![screen shot 2016-06-22 at 7 27 34 am](https://cloud.githubusercontent.com/assets/2131591/16265019/fc631bb0-384a-11e6-9675-f2c2e4227f0c.png)
![screen shot 2016-06-22 at 7 27 25 am](https://cloud.githubusercontent.com/assets/2131591/16265020/fc64f5ac-384a-11e6-9079-0dbdc77afa73.png)
![screen shot 2016-06-22 at 7 27 06 am](https://cloud.githubusercontent.com/assets/2131591/16265021/fc65182a-384a-11e6-86ce-febc30900692.png)

**Comment by aure** [comment]
Fixed by Elizabeth!
