### ISSUE TITLE
Missing Playground Page

### ISSUE THREAD

**Issue by narner** [audiokit/audiokit.github.io#84]
Currently, the page for the [Telephone Playground](http://audiokit.io/playgrounds/Telephone) is giving a 404 error.

**Comment by aure** [comment]
This particular page is fixed, but there are more problems with the playgrounds pages.  These are auto-generated from the AudioKit source, so the work you've already done on playgrounds show up here.  Also any mistakes do as well. :)  I'm cleaning it up but even when I'm done, it will be worth a closer look.
